for iX = 1:length(expInfo) 
    %find lists of trials with diff conditions happening in previous trial 
    [prevEarlyHit{iX}, ~] = selectCondition(expInfo(iX), [-1 -.5 -.12 -.05 0 .05 .12 .5 1],...
        behavioralData(iX), initTrialConditions('preStimMovement','quiescent'...
        'specificRTs',([.1 3]),'pastMovementTime','early','pastResponseType','correct'));

    [prevLateHit{iX}, ~] = selectCondition(expInfo(iX), [-1 -.5 -.12 -.05 0 .05 .12 .5 1],...
        behavioralData(iX), initTrialConditions('movementTime','late','preStimMovement','quiescent'...
        'specificRTs',([.1 3]),'pastMovementTime','late','pastResponseType','correct'));

    [prevEarlyMiss{iX}, ~] = selectCondition(expInfo(iX), [-1 -.5 -.12 -.05 0 .05 .12 .5 1],...
        behavioralData(iX), initTrialConditions('preStimMovement','quiescent'...
        'specificRTs',([.1 3]),'pastMovementTime','early','pastResponseType','incorrect'));

    [prevLateMiss{iX}, ~] = selectCondition(expInfo(iX), [-1 -.5 -.12 -.05 0 .05 .12 .5 1],...
        behavioralData(iX), initTrialConditions('movementTime','late','preStimMovement','quiescent'...
        'specificRTs',([.1 3]),'pastMovementTime','late','pastResponseType','incorrect'));

    %find list of trials with early vs late outcome in current trial 
    [earlyTrials{iX}, ~] = selectCondition(expInfo(iX), [-1 -.5 -.12 -.05 0 .05 .12 .5 1],...
        behavioralData(iX), initTrialConditions('movementTime','early','preStimMovement','quiescent'...
        'specificRTs',([.1 3])));

    [allTrials{iX}, ~] = selectCondition(expInfo(iX), [-1 -.5 -.12 -.05 0 .05 .12 .5 1],...
        behavioralData(iX), initTrialConditions('movementTime','all','preStimMovement','quiescent'...
        'specificRTs',([.1 3])));
    
    %calculate the fraction of 
    fractionEarly{iX} = 100 .* length(earlyTrials{iX}) ./ length(allTrials{iX});

end

violinplot(fractionEarly, xxx) 




