function dataLocations = dataPaths()
% add as many data locations to this list as you want. put your primary one
% first to break the search-loop faster

dataLocations = {...
    {'\\znas.cortexlab.net\Subjects'},...
    {'\\zserver.cortexlab.net\Data\Subjects'},... 
    {'\\zubjects.cortexlab.net\Subjects'}}; 
